#!/usr/bin/env php
<?php

require_once __DIR__.'/phpBBKernel.php';

use Symfony\Bundle\FrameworkBundle\Console\Application;

$kernel = new phpBBKernel('dev', true);

$application = new Application($kernel);
$application->run();
